### ISSUE TITLE
It is impossible to use the ZX-Uno core.

### ISSUE THREAD

**Issue by desUBIKado** [PetrM1/OndraSPO186_ZXUno#1]
I have installed it, but already the initial VGA image comes out with suspicious white pixels. If I press the ENTER key, the image starts to flicker.

The standard keys for SOFT RESET (CTRL+ALT+DEL) and HARD RESET (CTRL+ALT+BACKSPACE) are not configured.

Let's see if a second version comes out that fixes these bugs, but now it's unusable.

**Comment by PetrM1** [comment]
Hello desUBIKado,
Unfortunately neither of my 2 ZX Uno (original one but with 2Mb SRAM and Manu FerHi’s  ZX Uno VGA 2M) were having this “pixel issue”. I was seeing clear picture, same as on video captured on MiSTer. Luckily friend of mine reported same issue as you have so we could to some remote fixing and debugging 😊 Hope recent version will be working for you. I’ve also included Soft and Hard reset and I’ve learned about existence of ICAP_SPARTAN6 – thank you for that request.

Could you test it and close the issue if fixed, please?

And just out of curiosity, could you describe your ZX Uno in more detail, please? I’m mostly interested in your SRAM module installed.

Thank you
Petr
